config/routes.rb
Facemate::Application.routes.draw do
	root to: "users#index" 

  devise_for :users 

  resources :users, only: [:index, :show, :edit, :update] do
  	resources :photos, only: [:index, :show]
  	resources :messages
    resources :likings
    resources :shunnings
  end

  resources :types

  resources :photos

  resources :messages

  resources :visits

  resources :ratings

  resources :feedbacks

  resources :likings

  resources :shunnings


  match "/users/:id/profile" => "users#profile_edit"
  match "/face_matches" => "users#face_matches"
  match "/browse" => "users#browse"
  match "/blacklist" => "users#blacklist"
end

app/models/message.rb
class Message < ActiveRecord::Base
	attr_accessible :sender_id, :recipient_id, :body, :read

	# validates :sender_id, :recipient_id, :body, presence: true

	belongs_to :sender, class_name: "User", foreign_key: :sender_id
	belongs_to :recipient, class_name: "User", foreign_key: :recipient_id
end 

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
	before_filter :authenticate_user!
	before_filter :update_last_seen

	def index 
		if params[:user_id]
			partner_id = params[:user_id]
			@partner = User.find(partner_id)
			@conversation = Message.where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', current_user.id, partner_id , partner_id , current_user.id).order('id DESC')
		else
			conversation_partner_ids = current_user.conversation_partners.map { |partner| partner.id }
			
			@conversations = []
			
			conversation_partner_ids.each do |cpi|
				@conversations << Message.where('(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)', current_user.id, cpi, cpi, current_user.id).order('id DESC')
			end

			@conversations.each do |convo|
				convo.sort_by! {|mess| mess.id }
			end

			@conversations.sort_by! {|convo| convo[-1].id }.reverse!
			@inbox = @conversations.map do |convo| 
				last_message_in = convo.rindex { |message| message.recipient_id == current_user.id } 
				if last_message_in
					convo[0..last_message_in]
				else
					convo
				end
			end
			@awaiting_reply = @conversations.map do |convo| 
				last_message_in = convo.rindex { |message| message.recipient_id == current_user.id } 
				if last_message_in 
					convo[(last_message_in + 1)..-1]
				else
					convo
				end
			end.select { |convo| !convo.empty? }
		end

		if request.xhr?
			render partial: "all_messages_in_convo"
		else
			render :index
		end
	end


	def create
		@message = Message.new(params[:message])
		@message.sender_id = current_user.id

		@message.save! 

		if request.xhr?
			render partial: "added_message", locals: {message: @message}
		else
			redirect_to messages_url
		end
	end

end 

app/views/messages/_added_message.html.erb
<div class="added-message group">
<% if message.sender_id == current_user.id %>
	<div class="outgoing-message pull-right">
		<div class="single-message group">
			<div class="single-message-body-right bubble-right">
		    <p><%= message.body %></p>
		  </div>

			<header class="single-message-header-right group">
				<div class="single-message-thumb">
					<% if current_user.profile_pic %>
						<a href="#"><img src="<%= current_user.profile_pic.image.url(:thumb) %>" alt="" width="50" height="50"></a>
					<% else %>
						<div class="small-anon-pic">
							<a href="#"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" alt="" width="50" height="50"></a>
						</div>
					<% end %>
				</div>
				<div class="single-message-info">
					<h2><a href="#">
						You
						</a></h2>
					<time><%= time_ago_in_words(message.created_at) + " ago" %></time>
				</div>
			</header>
		</div>
	</div>

<% else %>

	<div class="single-message group">
	 	<header class="single-message-header-left group">
			<div class="single-message-thumb">
				<% if %>
					<a href="#"><img src="<%= User.find(message.sender_id).profile_pic.image.url(:thumb) %>" alt="" width="50" height="50"></a>
				<% else %>
					<div class="small-anon-pic">
						<a href="#"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" alt="" width="50" height="50"></a>
					</div>
				<% end %>
			</div>
			<div class="single-message-info">
				<h2><a href="#">
					<%= User.find(message.sender_id).username %>
					</a></h2>
				<time><%= time_ago_in_words(message.created_at) + " ago" %></time>
			</div>
		</header>

		<div class="single-message-body-left bubble-left">
	    <p><%= message.body %></p>
	  </div>
	</div>

<% end %> 

</div>

app/views/messages/_all_messages_in_convo.html.erb
<% @conversation.each do |mess| %>
		<% if mess.sender_id == @partner.id %>
			<% mess.read = true %>
			<% mess.save! %>
			<div class="message-container group">
				<div class="incoming-message pull-left"> 							
					<%= render partial: "message", locals: {message: mess} %>
				</div>
			</div>
		<% else %>
			<div class="message-container group">
				<div class="outgoing-message pull-right"> 							
					<%= render partial: "message", locals: {message: mess} %>
				</div>
			</div>
		<% end %> 

<% end %> 

app/views/messages/_message.html.erb
<section class="messages">
	<article class="message">


		<% if message.sender_id == current_user.id %>
			<div class="single-message group">
				<div class="single-message-body-right bubble-right">
	        <p><%= message.body %></p>
	      </div>

				<header class="single-message-header-right group">
					<div class="single-message-thumb">
						<% if current_user.profile_pic %>
							<a href="#"><img src="<%= current_user.profile_pic.image.url(:thumb) %>" alt="" width="50" height="50"></a>
						<% else %>
							<div class="small-anon-pic"> 
								<a href="#"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" alt="" width="50" height="50"></a>
							<div> 
						<% end %>
					</div>
					<div class="single-message-info">
						<h2><a href="#">
							You
							</a></h2>
						<time><%= time_ago_in_words(message.created_at) + " ago" %></time>
					</div>
				</header>
			</div>

      

   	<% else %>

   		<div class="single-message group">
		   	<header class="single-message-header-left group">
					<div class="single-message-thumb">
						<% if User.find(message.sender_id).profile_pic %>
							<a href="#"><img src="<%= User.find(message.sender_id).profile_pic.image.url(:thumb) %>" alt="" width="50" height="50"></a>
						<% else %>
							<div class="small-anon-pic">
								<a href="#"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" alt="" width="50" height="50"></a>
							</div>
						<% end %>
					</div>
					<div class="single-message-info">
						<h2><a href="#">
							<%= User.find(message.sender_id).username %>
							</a></h2>
						<time><%= time_ago_in_words(message.created_at) + " ago" %></time>
					</div>
				</header>

	    	<div class="single-message-body-left bubble-left">
	        <p><%= message.body %></p>
	      </div>
      </div>

   	<% end %> 

	</article>

</section> 

app/views/messages/_message_form.html.erb
<%= form_for(Message.new, remote: true, html: {id: "new-message-form"}) do |f| %>
	<%= f.text_area :body, :style => "width: 380px; border-radius: 15px", :rows => "5" %>
	<%= hidden_field_tag "message[recipient_id]", user_id %> 
	<br> 
	<div class="message-submit group">
		<% if @partner %>
			<h2 class="message-submit-prompt">Say something to <%= @partner.username %></h2>
		<% else %>
			<h2 class="message-submit-prompt">Say something to <%= @user.username %></h2>
		<% end %>
		<div class="message-submit-button">
			<%= f.submit "Send", :class => "btn" %>
		</div> 
	</div>
<% end %> 


<script> 
	
	$(document).ready(function () {
		
		$("#new-message-form").on("ajax:success", function (event, data) {
			var convoMessages = $(".convo-messages")

			if (<%= on_profile %>) {
				alert("Your message was sent!")
			} 
			else {
				$(".convo-messages").prepend(data);
			}
			

			$("#message_body").val("");

		});

	});

</script> 

app/views/messages/index.html.erb
<div class="homepage">
	<div class="home-header group">
		<div class="page-title">
			<% if @partner %>
				<h1>Conversation with <%= @partner.username %></h1>
			<% else %>
				<h1>Messages</h1>
			<% end %>
		</div> 
	</div>


	<div class="messages-main">
		<% if @conversations %>
			<div class="tabbable">
			  <ul class="nav nav-tabs">
			    <li class="active"><a href="#tab1" data-toggle="tab">Inbox</a></li>
			    <li><a href="#tab2" data-toggle="tab">Awaiting Reply</a></li>
			    <li><a href="#tab3" data-toggle="tab">Trash</a></li>
			  </ul>
			  <div class="tab-content">
			    <div class="tab-pane active" id="tab1">
			      <% @inbox.each do |convo| %>
			      	<% if convo.last.recipient.id == current_user.id %>
			      		<div class="message-snipet group"> 
			      			<div class="snipet-header">
									<% other_person = convo.last.sender %>
									<a href="/users/<%= other_person.id %>">
										<div class="single-message-thumb">
											<% if other_person.profile_pic %>
												<img src="<%= other_person.profile_pic.image.url(:thumb) %>" alt="" width="50" height="50">
											<% else %>
												<div class="small-anon-pic">
													<img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" alt="" width="50" height="50">
												</div>
											<% end %>
										</div>
										<%= other_person.username %><br>
									</a>
										<% if convo.any? {|message| message.read != true } %>
											<strong>*new message*</strong>
											<br>
										<% end %>
										<%= "Recieved " + time_ago_in_words(convo.last.created_at) + " ago" %>
									</div>
									<div class="snipet-preview">
										<a href="/users/<%= other_person.id %>/messages"><p>
											<%= convo.last.body.length > 500 ? convo.last.body[0..500] + "..." : convo.last.body %>
										</p></a>
									</div>
		 						</div>
		 						<hr>
							<% end %>
			      <% end %>
			    </div>
			    <div class="tab-pane" id="tab2">
			      <% @awaiting_reply.each do |convo| %>
			      	<% if convo.last.recipient.id != current_user.id %>
								<% other_person = convo.last.recipient %>
								<a href="/users/<%= other_person.id %>/messages">
									<%= "You sent a message to: " + other_person.username %><br>
								</a>
									<%= time_ago_in_words(convo.last.created_at) + " ago" %>
								<hr>
							<% end %>
			      <% end %>
			    </div>
			    <div class="tab-pane" id="tab3">
			      <p>Nothing here yet...</p>
			    </div>
			  </div>
			</div>

		<% elsif @conversation %>

			<section class="messages">
				<article class="message">

					<header class="message-header group">

						<div class="message-form">
			        <%= render partial: "message_form", locals: {user_id: params[:user_id], on_profile: false} %> 
			      </div>
					</header>

			      
			   
				</article>
			</section> 

			
      <div class="convo-messages">
      	<%= render partial: "all_messages_in_convo" %>
			</div>	


		<% end %>
	</div>


</div>


<script>
	
	$convoMessages = $(".convo-messages")

	$(document).ready(function () {

		<% if @partner %>
			window.setInterval(function() {

				$.ajax({
					url: "<%= messages_path %>",
					type: "GET",
					data: {
						"user_id" : <%= @partner.id %>
						},
					success: function(data) {
						$convoMessages.empty();
						$convoMessages.html(data);
					}
				});
			},1000);
		<% end %>

	});
	
</script> 