config/routes.rb
Facemate::Application.routes.draw do
	root to: "users#index" 

  devise_for :users 

  resources :users, only: [:index, :show, :edit, :update] do
  	resources :photos, only: [:index, :show]
  	resources :messages
    resources :likings
    resources :shunnings
  end

  resources :types

  resources :photos

  resources :messages

  resources :visits

  resources :ratings

  resources :feedbacks

  resources :likings

  resources :shunnings


  match "/users/:id/profile" => "users#profile_edit"
  match "/face_matches" => "users#face_matches"
  match "/browse" => "users#browse"
  match "/blacklist" => "users#blacklist"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable
         # , :confirmable

  attr_accessor :login
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :login, 
  								:password, :password_confirmation, :remember_me,
                  :num_likes, :last_like_refresh,
                  :birthdate, :sex, :zipcode,
                  :height, :weight, :body_type,
                  :relationship_status, :ethnicity, :orientation,
                  :about_me, :about_my_match, :dealbreakers

	def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    where(conditions).first
	  end
	end
  
  attr_accessor :face_matches

  def profile_pic
    self.photos.where(is_user: true, is_profile_pic: true).first || self.photos.where(is_user: true).first
  end

  has_many :photos

  has_many :types

  has_many :occurances_as_match, class_name: "TypeMatch", foreign_key: :user_id

  # VISITS
  has_many :visited_profiles, class_name: "Visit", foreign_key: :visitor_id
  has_many :visitings, class_name: "Visit", foreign_key: :visitee_id

  has_many :visitors, through: :visitings, source: :visitor 
  has_many :visited_users, through: :visited_profiles, source: :visitee

  # LIKINGS
  has_many :likes_given, class_name: "Liking", foreign_key: :liking_user_id
  has_many :likes_received, class_name: "Liking", foreign_key: :liked_user_id

  has_many :users_who_like_me, through: :likes_received, source: :liker
  has_many :users_ive_liked, through: :likes_given, source: :likee

  # SHUNNING
  has_many :shuns_given, class_name: "Shunning", foreign_key: :shunning_user_id
  has_many :shuns_received, class_name: "Shunning", foreign_key: :shunned_user_id

  has_many :users_who_shun_me, through: :shuns_received, source: :shunner
  has_many :users_ive_shunned, through: :shuns_given, source: :shunnee

  # RATINGS
  has_many :ratings_given, class_name: "Rating", foreign_key: :rating_giver_id
  has_many :ratings_received, class_name: "Rating", foreign_key: :rating_receiver_id

  has_many :users_who_rated_me, through: :ratings_received, source: :rater
  has_many :users_ive_rated, through: :ratings_given, source: :ratee

  def avg_rating
    total_score = 0 
    self.ratings_received.each { |rating| total_score += rating.score }
    avg_rating = total_score / self.ratings_received.size.to_f
    avg_rating
  end

  # FEEDBACKS
  has_many :feedbacks_given, class_name: "Feedback", foreign_key: :feedback_giver_id
  has_many :feedbacks_received, class_name: "Feedback", foreign_key: :feedback_receiver_id

  has_many :users_who_gave_me_feedback, through: :feedbacks_received, source: :feedback_giver
  has_many :users_ive_given_feedback, through: :feedbacks_given, source: :feedback_receiver

  # MESSAGES
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id

  has_many :requested_conversation_partners, through: :sent_messages, source: :recipient 
  has_many :requesting_conversation_partners, through: :received_messages, source: :sender 

  def conversation_partners
    (self.requested_conversation_partners + self.requesting_conversation_partners).uniq
  end

  def shunned_pairs
    (self.users_who_shun_me + self.users_ive_shunned).uniq
  end


  # ***API METHODS***
  def find_pic_gender(pic)
    api_key = "EANeodQhAiTEapGd"
    api_secret = "aMAD2iBa1vtIRoI9"
    jobs = "face_gender"
    urls = pic.image.url
    app_name = "facemate_beta1_gender"

    response = Unirest::post("http://rekognition.com/func/api/?api_key=#{api_key}&api_secret=#{api_secret}&jobs=#{jobs}&urls=#{urls}&name_space=#{app_name}")  

    results = response.body["face_detection"][0]["sex"]
    results < 0.5 ? "female" : "male"
  end

  def add_pic_to_album(pic)
    #this does the work of calling the API with add method
    #there are albums for men and women. 
    #if the person hasn't specified their own gender one will be assigned to them. 
    # facemate album buckets are currently facemate_beta1_male and facemate_beta1_female
    if self.sex.nil?
      gender = find_pic_gender(pic)
      gender == "male" ? self.sex = "Male" : "Female"
      self.save!
    end

    api_key = "EANeodQhAiTEapGd"
    api_secret = "aMAD2iBa1vtIRoI9"
    jobs = "face_add_[#{self.username}]"
    urls = pic.image.url

    if self.sex == "Male"
      app_name = "facemate_beta1_male"
    else
      app_name = "facemate_beta1_female"
    end

    Unirest::post("http://rekognition.com/func/api/?api_key=#{api_key}&api_secret=#{api_secret}&jobs=#{jobs}&urls=#{urls}&name_space=#{app_name}")
  end

  def add_all_pics_to_album
    photos_of_me = self.photos.select { |photo| photo.is_user == true && photo.photo_type == "face" }
    photos_of_me.each { |pic| add_pic_to_album(pic) }
  end


  def train_album
    # facemate album buckets are currently facemate_beta1_male and facemate_beta1_female
    api_key = "EANeodQhAiTEapGd"
    api_secret = "aMAD2iBa1vtIRoI9"
    jobs = "face_train"
    app_name1 = "facemate_beta1_male"
    app_name2 = "facemate_beta1_female"

    Unirest::post("http://rekognition.com/func/api/?api_key=#{api_key}&api_secret=#{api_secret}&jobs=#{jobs}&name_space=#{app_name1}")
    Unirest::post("http://rekognition.com/func/api/?api_key=#{api_key}&api_secret=#{api_secret}&jobs=#{jobs}&name_space=#{app_name2}")
  end
  # ****END API METHODS***

  def deselected_users
    #filters out users that have shunned you or you have shunned
    #filters out conversation partners
    #filters you out of the results!
    results = User.all
    results.select! { |user| user.id != self.id }
    # results.select! { |user| !self.conversation_partners.include?(user) }
    results.select! { |user| !self.shunned_pairs.include?(user) }
    results
  end

  def average_results(results)
    users = results.map { |result| result[0] }.uniq

    users_scores = users.map do |user|
      user_events = results.select {|result| result[0] == user}
      sum = 0
      user_events.each { |event| sum += event[1] }
      avg = sum.to_f / user_events.size
      [user, avg]
    end

    users_scores.sort_by { |user_score| user_score[1] }.reverse
  end

  def find_face_matches_for_all_types
    matches = [] 
    self.try(:types).try(:each) {|type| matches += type.try(:find_all_matches) }
    @face_matches = average_results(matches)
    @face_matches.select! { |match| match[0] != self.username }

    @face_matches.map { |match| User.find_by_username(match[0]) }
  end

  #add in similar face matches later!

  def best_matches
    #use this for the front page photo grid
    #should exclude people you're already talking to
    #should exclude people you've shunned and who have shunned you
    #should prioritize face matches
    #should give second priority to people who have liked you
    #should give third priority to new members
    #should fill in the rest with whatever

    deselected_ids = self.deselected_users.map { |user| user.id }
    # like_matches = results.select { |result| self.users_who_like_me.include?(result) }
    face_matches = self.find_face_matches_for_all_types
    # all_matches = (face_matches + like_matches).uniq
    # all_matches ## this used to be returned, the algo needs tweaking
    face_matches.compact.select { |user| deselected_ids.include?(user.id) }
  end

  def remaining_likes
    if Date.today - self.last_like_refresh > 0
      self.last_like_refresh = Date.today
      self.num_likes = 5
      self.save!
      self.num_likes
    else
      self.num_likes
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	before_filter :authenticate_user!
	before_filter :update_last_seen


	# log_visit requires "id" in the params to correspond to a user's id
	after_filter :log_visit
	skip_after_filter :log_visit, only: [:new, :create, :index, :destroy, :edit, :update]

	def show
		@user = User.find(params[:id])

		if current_user.users_who_shun_me.include?(@user)
			flash[:notice] = "You have been shunned!"
			redirect_to root_url
		end
	end

	def index
		if params[:page] && params[:page].to_i > 1
			start = (params[:page].to_i - 1) + ((params[:page].to_i - 1) * 5)
			stop = 5 + start
		else
			start = 0
			stop = 5
			params[:page] = 0
			first_page = true 
		end 

		case params[:index]
		when "browse"
			@users = current_user.deselected_users.sort_by! do |user| 
				Liking.where(liking_user_id: user.id, liked_user_id: current_user.id).size
			end.reverse
			@user_index = "browse"
		when "blacklist"
			@users = current_user.users_ive_shunned
			@user_index = "blacklist"
		when "matches"
			@users = current_user.best_matches
			@user_index = "matches"
		else 
			@users = current_user.deselected_users.sort_by! {|user| user.id }.reverse
			@user_index = "main"
		end

		total_pages = (@users.size / 6.0).ceil
		total_pages = 1 if total_pages == 0
		@users = @users[start..stop]

		return redirect_to new_type_path if @user_index == "matches" && @users.size == 0

		if request.xhr?
			render partial: "users/master_browse", locals: {first_page: first_page, total_pages: total_pages, page: params[:page]}
		else
			render :index, locals: {first_page: first_page, total_pages: total_pages, page: params[:page]}
		end
	end

	def edit
		@user = current_user
	end

	def profile_edit
		@user = current_user
	end

	def update
		@user = current_user
		
		if @user.update_attributes(params[:user])
			if request.xhr?
				render partial: "users/profile"
			else
				redirect_to user_url(current_user)
			end
		else 
			redirect_to user_url(current_user)
		end
	end

end 

app/views/users/_master_browse.html.erb
<div class="photoscroll">
	<div class="grid-container group">
		<div class="photogrid group">
			<% if @users.empty? %>
				<h1>Hmmmm... nothing here</h1>
			<% end %>
			<% @users.each do |user| %>
				<div class="replace-user" id="replace-user-<%= user.id %>">
					<%= render partial: "profile_display", locals: {user: user} %>
				</div>
			<% end %> 
		</div> 
	</div>
	
</div> 



<script>
	

	$(document).ready(function () {

		var $next = $("#next-6")
		var $previous = $("#previous-6")
		var $browseMaster = $(".browse-master")

		var $remainingLikes = $(".remaining-likes")

		<% @users.each do |user| %>

			$.ajax({
				url: "users/<%= user.id %>/likings",
				type: "GET",
				data: {
						"liked_user_id" : "<%= user.id %>",
					},
				success: function(data) {
					var $totalLikes = $("#total-likes-<%= user.id %>")
					$totalLikes.html(data);
				}
			});
			

			var $likeAction = $("#like-action-<%= user.id %>")


			$likeAction.on("click", function (event) {

				$.ajax({
					url: "<%= likings_path %>",
					type: "POST",
					data: {
							"liked_user_id" : "<%= user.id %>",
							"liking_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						$remainingLikes.empty();
						$remainingLikes.html(data);
						$.ajax({
							url: "users/<%= user.id %>/likings",
							type: "GET",
							data: {
									"liked_user_id" : "<%= user.id %>",
								},
							success: function(data) {
								var $totalLikes = $("#total-likes-<%= user.id %>")
								$totalLikes.empty();
								$totalLikes.html(data);
							}
						});
						
					}
				});

			});


			var $shunAction = $("#shun-action-<%= user.id %>")

			$shunAction.on("click", function (event) {

				$.ajax({
					url: "<%= shunnings_path %>",
					type: "POST",
					data: {
							"shunned_user_id" : "<%= user.id %>",
							"shunning_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						// explode really doesn't seem to look right, but kind of works
						var $shunnedUser = $("#replace-user-<%= user.id %>") 
						var $shunnedUserImage = $("#user-pic-<%= user.id %>") 
						$shunnedUserImage.effect("explode", {pieces: 9}, 1000);
						$shunnedUser.empty();
						$shunnedUser.addClass(".destroyed");
					}
				});


				$.ajax({
				url: "/",
				type: "GET",
				data: {
						"page" : <%= page %>,
						"index" : "<%= @user_index %>"
					},
				success: function(data) {
					<% if @users.size <= 6 %> 
						$next.addClass("destroyed");
					<% end %>
					$browseMaster.empty();
					$browseMaster.html(data);
					}
				});		

			});


			var $UnShunAction = $("#unshun-action-<%= user.id %>")

			$UnShunAction.on("click", function (event) {

				$.ajax({
					url: "<%= shunning_path(user) %>",
					type: "DELETE",
					data: {
							"shunned_user_id" : "<%= user.id %>",
							"shunning_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						// explode really doesn't seem to look right, but kind of works
						var $shunnedUser = $("#replace-user-<%= user.id %>") 
						var $shunnedUserImage = $("#user-pic-<%= user.id %>") 
						$shunnedUserImage.effect("explode", {pieces: 9}, 1000);
						$shunnedUser.empty();
						$shunnedUser.addClass(".destroyed");
					}
				});

				$.ajax({
					url: "/",
					type: "GET",
					data: {
							"page" : <%= page %>,
							"index" : "<%= @user_index %>"
						},
					success: function(data) {
						<% if @users.size <= 6 %> 
							$next.addClass("destroyed");
						<% end %>
						$browseMaster.empty();
						$browseMaster.html(data);
					}
				});	

			});


		<% end %> 




	});


</script> 

app/views/users/_online_now.html.erb
<!-- requires a local for the user -->

<div class="online-now">
	<% if user.last_seen %>
		<%= "Online Now" if Time.now - user.last_seen < 300 %>
	<% end %> 
</div>

app/views/users/_profile_display.html.erb
<div class="photo-frame">

	<div class="user-frame" id="user-frame-<%= user.id %>">
		
		<% if user.profile_pic %> 
			<a href="/users/<%= user.id %>">
				<img src="<%= user.profile_pic.image.url(:small) %>" id="user-pic-<%= user.id %>">
				<%= render partial: "users/online_now", locals: {user: user} %>
			</a>
		<% else %> 
			<a href="/users/<%= user.id %>"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" width="225px" height="225px"></a>
		<% end %>
		<% if user.id != current_user.id %>
			<div class="user-interactions group">
				<% if @user_index == "blacklist" %>
					<div class="display-name">
						<%= user.username %>
					</div>
					<div class="unshun-container">
						<div class="unshun-action btn btn-danger" id="unshun-action-<%= user.id %>">Un-Shun</div>
					</div>
				<% else %>
					<div class="display-name">
						<%= user.username %>
					</div>
					<div class="like-action btn btn-info" id="like-action-<%= user.id %>">Like</div>
					<div class="shun-action btn btn-danger" id="shun-action-<%= user.id %>">Shun</div>
				<% end %>
			</div>


		<% else %>
			<div class="user-interactions group">
				<div class="display-name">
					<%= user.username %>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/users/_remaining_likes.html.erb
<% if remaining_likes > 0 %>
	<span class="label label-info">Remaining Likes: <%= remaining_likes %></span>
<% else %>
	<span class="label label-inverse">Remaining Likes: 0</span>
	<p>You'll get more tomorrow, don't worry!</p>
<% end %>

app/views/users/_results_display.html.erb
<div class="photo-frame">

	<div class="user-frame" id="user-frame-<%= user.id %>">
		<div class="display-name">
			<%= user.username %>
		</div>
		<% if user.profile_pic %> 
			<a href="/users/<%= user.id %>">
				<img src="<%= user.profile_pic.image.url(:small) %>" id="user-pic-<%= user.id %>">
				<%= render partial: "users/online_now", locals: {user: user} %>
			</a>
		<% else %> 
			<a href="/users/<%= user.id %>"><img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTzokyVmgb8OiC4dVtoGcHXFAhvzyqm1TmDssGtKE-l0oYU66ut" width="225px" height="225px"></a>
		<% end %>
		<div class="user-interactions group">
<!-- 			<%#= render partial: "users/small_stats", locals: {user: user} %> -->
<!-- 			<div class="total-likes" id="total-likes-<%= user.id %>"></div> -->
			<div class="like-action btn btn-info" id="like-action-<%= user.id %>">Like</div>
			<div class="shun-action btn btn-danger" id="shun-action-<%= user.id %>">Shun</div>
		</div>
	</div>

</div>

app/views/users/_shunned_grid.html.erb
<% if @users.empty? %>
	<h1>Hmmmm... nothing here</h1>
<% end %>
<% @users.each do |user| %>
	<%= render partial: "shunned_view", locals: {user: user} %>
<% end %> 

app/views/users/blacklist.html.erb
<div class="homepage">
	<div class="home-header group">

		<div class="page-title">
			<h1>Shunned Users</h1>
		</div> 
	</div>

	<div class="photoscroll">
		<div class="grid-container group">
			<div class="photogrid group">
				<%= render partial: "shunned_grid" %>
			</div> 
		</div>
		<div class="photogrid-nav group">
			<div class="btn" id="previous-6">
				Previous
			</div> 
			<div class="btn" id="next-6">
				Next 
			</div>
		</div> 
	</div> 

</div>


<script>
	

	$(document).ready(function () {


		var pageCounter = 1

		var $next = $("#next-6")
		var $previous = $("#previous-6")
		var $gridContainer = $(".grid-container")

		if (pageCounter == <%= total_pages %>) {
			$next.addClass("destroyed");
		}

		if (pageCounter == 1) {
			$previous.addClass("destroyed");
		}


		$next.on("click", function () {
			pageCounter += 1
			

			$.ajax({
				url: "/blacklist",
				type: "GET",
				data: {
						"page" : pageCounter,
					},
				success: function(data) {
					$gridContainer.empty();
					$gridContainer.html(data);
					if ($previous.hasClass("destroyed")) {
						$previous.removeClass("destroyed");
					}
					if (pageCounter == <%= total_pages %>) {
						$next.addClass("destroyed");
					}
				}
			});

		});


		$previous.on("click", function () {
			pageCounter -= 1

			$.ajax({
				url: "/blacklist",
				type: "GET",
				data: {
						"page" : pageCounter,
					},
				success: function(data) {
					$gridContainer.empty();
					$gridContainer.html(data);
					if ($next.hasClass("destroyed")) {
						$next.removeClass("destroyed");
					}
					if (pageCounter == 1) {
						$previous.addClass("destroyed");
					}
				}
			});

		});

		<% @users.each do |user| %>

			var $UnShunAction = $("#unshun-action-<%= user.id %>")

			$UnShunAction.on("click", function (event) {

				$.ajax({
					url: "<%= shunning_path(user) %>",
					type: "DELETE",
					data: {
							"shunned_user_id" : "<%= user.id %>",
							"shunning_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						// explode really doesn't seem to look right, but kind of works
						var $shunnedUser = $("#user-frame-<%= user.id %>") 
						var $shunnedUserImage = $("#user-pic-<%= user.id %>") 
						$shunnedUserImage.effect("explode", {pieces: 9}, 1000);
						$shunnedUser.empty();
						$shunnedUser.addClass(".destroyed");
					}
				});

			});

		<% end %> 




	});


</script> 

app/views/users/face_matches.html.erb
<div class="homepage">
	<div class="home-header group">

		<div class="page-title">
			<h1>Face Matches</h1>
		</div> 
	</div>

	<div class="photoscroll">
		<div class="grid-container group">
			<div class="photogrid group">
				<% if @users.empty? %>
					<h1>Hmmmm... nothing here</h1>
				<% end %>
				<% @users.each do |user| %>
					<%= render partial: "profile_display", locals: {user: user} %>
				<% end %> 
			</div> 
		</div>
		<div class="photogrid-nav group">
			<div class="btn" id="previous-6">
				Previous
			</div> 
			<div class="btn" id="next-6">
				Next 
			</div>
		</div> 
	</div> 

</div>


<script>
	

	$(document).ready(function () {

		var pageCounter = 1

		var $next = $("#next-6")
		var $previous = $("#previous-6")
		var $gridContainer = $(".grid-container")

		if (pageCounter == <%= total_pages %>) {
			$next.addClass("destroyed");
		}

		if (pageCounter == 1) {
			$previous.addClass("destroyed");
		}


		$next.on("click", function () {
			pageCounter += 1
			

			$.ajax({
				url: "/face_matches",
				type: "GET",
				data: {
						"page" : pageCounter,
					},
				success: function(data) {
					$gridContainer.empty();
					$gridContainer.html(data);
					if ($previous.hasClass("destroyed")) {
						$previous.removeClass("destroyed");
					}
					if (pageCounter == <%= total_pages %>) {
						$next.addClass("destroyed");
					}
				}
			});

		});


		$previous.on("click", function () {
			pageCounter -= 1

			$.ajax({
				url: "/face_matches",
				type: "GET",
				data: {
						"page" : pageCounter,
					},
				success: function(data) {
					$gridContainer.empty();
					$gridContainer.html(data);
					if ($next.hasClass("destroyed")) {
						$next.removeClass("destroyed");
					}
					if (pageCounter == 1) {
						$previous.addClass("destroyed");
					}
				}
			});

		});

		var $remainingLikes = $(".remaining-likes")

		<% @users.each do |user| %>

			$.ajax({
				url: "users/<%= user.id %>/likings",
				type: "GET",
				data: {
						"liked_user_id" : "<%= user.id %>",
					},
				success: function(data) {
					var $totalLikes = $("#total-likes-<%= user.id %>")
					$totalLikes.html(data);
				}
			});
			

			var $likeAction = $("#like-action-<%= user.id %>")


			$likeAction.on("click", function (event) {

				$.ajax({
					url: "<%= likings_path %>",
					type: "POST",
					data: {
							"liked_user_id" : "<%= user.id %>",
							"liking_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						console.log("success!");
						$remainingLikes.empty();
						$remainingLikes.html(data)
						$.ajax({
							url: "users/<%= user.id %>/likings",
							type: "GET",
							data: {
									"liked_user_id" : "<%= user.id %>",
								},
							success: function(data) {
								var $totalLikes = $("#total-likes-<%= user.id %>")
								$totalLikes.empty();
								$totalLikes.html(data);
							}
						});
					}
				});

			});


			var $shunAction = $("#shun-action-<%= user.id %>")

			$shunAction.on("click", function (event) {

				$.ajax({
					url: "<%= shunnings_path %>",
					type: "POST",
					data: {
							"shunned_user_id" : "<%= user.id %>",
							"shunning_user_id" : "<%= current_user.id %>"  
						},
					success: function(data) {
						// explode really doesn't seem to look right, but kind of works
						var $shunnedUser = $("#user-frame-<%= user.id %>") 
						var $shunnedUserImage = $("#user-pic-<%= user.id %>") 
						$shunnedUserImage.effect("explode", {pieces: 9}, 1000);
						$shunnedUser.empty();
						$shunnedUser.addClass(".destroyed");
					}
				});

			});

		<% end %> 




	});


</script> 

app/views/users/show.html.erb
<div class="homepage">
	<div class="home-header group">

		<div class="page-title">
			<h1><%= @user.username %>'s page</h1>
		</div> 
	</div>

	<div class="profile-head group">
		<div class="user-picture"> 
			<%= render partial: "users/small_user", locals: {user: @user} %>
		</div>

		<div class="user-details">
			<%= render partial: "users/small_stats", locals: {user: @user} %>
			<%= render partial: "users/vital_stats" %>
			<% if @user.id == current_user.id %>
				<a href="<%= edit_user_path(@user) %>">Edit Details</a>
			<% end %>
		</div>
		<% if current_user.id != @user.id %> 
			<div class="profile-message-form">
				<%= render partial: "messages/message_form", locals: {user_id: params[:id], on_profile: true} %>
			</div> 
		<% end %>
	</div>

	<div id="add-pics">
		<% if @user.id == current_user.id %>
			<a href="<%= new_photo_path %>">(add photos)</a>
		<% end %> 
	</div>

	<section class="bottom-profile-container">
		


		<div class="personal-essays-container">
			<div id="about-me">
				<h1>How I Ended Up Here</h1>
				<p><%= @user.about_me.nil? ? "Nothing here yet..." : @user.about_me %></p>
			</div>
			<div id="about-my-match">
				<h1>What I'll Settle For</h1>
				<p><%= @user.about_my_match.nil? ? "Nothing here yet..." : @user.about_my_match %></p>
			</div>
			<div id="dealbreakers">
				<h1>But No Way Will I Accept</h1>
				<p><%= @user.dealbreakers.nil? ? "Nothing here yet..." : @user.dealbreakers %></p>
			</div>
			<% if @user.id == current_user.id %>
				<a href="<%= current_user.id %>/profile">Edit Essays</a>
			<% end %>
		</div> 
		

	</section>

</div> 




<script>

	$(document).ready(function () {

	var $remainingLikes = $(".remaining-likes")

			$.ajax({
				url: "<%= @user.id %>/likings",
				type: "GET",
				data: {
						"liked_user_id" : "<%= @user.id %>",
					},
				success: function(data) {
					var $totalLikes = $("#total-likes-<%= @user.id %>")
					$totalLikes.empty();
					$totalLikes.html(data);
				}
			});
			

		var $likeAction = $("#like-action-<%= @user.id %>")

		$likeAction.on("click", function (event) {

			$.ajax({
				url: "<%= likings_path %>",
				type: "POST",
				data: {
						"liked_user_id" : "<%= @user.id %>",
						"liking_user_id" : "<%= current_user.id %>"  
					},
				success: function(data) {
					$remainingLikes.empty();
					$remainingLikes.html(data)
					$.ajax({
						url: "<%= @user.id %>/likings",
						type: "GET",
						data: {
								"liked_user_id" : "<%= @user.id %>",
							},
						success: function(data) {
							var $totalLikes = $("#total-likes-<%= @user.id %>")
							$totalLikes.empty();
							$totalLikes.html(data);
						}
					});
				}
			});

		});


		var $shunAction = $("#shun-action-<%= @user.id %>")

		$shunAction.on("click", function (event) {

			$.ajax({
				url: "<%= shunnings_path %>",
				type: "POST",
				data: {
						"shunned_user_id" : "<%= @user.id %>",
						"shunning_user_id" : "<%= current_user.id %>",
						"on_profile" : "true"						
					},
				success: function() {
					window.location = "<%= root_url %>";
				}
			});

		});

	});


</script>