config/routes.rb
Facemate::Application.routes.draw do
	root to: "users#index" 

  devise_for :users 

  resources :users, only: [:index, :show, :edit, :update] do
  	resources :photos, only: [:index, :show]
  	resources :messages
    resources :likings
    resources :shunnings
  end

  resources :types

  resources :photos

  resources :messages

  resources :visits

  resources :ratings

  resources :feedbacks

  resources :likings

  resources :shunnings


  match "/users/:id/profile" => "users#profile_edit"
  match "/face_matches" => "users#face_matches"
  match "/browse" => "users#browse"
  match "/blacklist" => "users#blacklist"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :user_id, :photo_type, :photo_age, :approved, 
									:single_person, :is_user, :is_profile_pic, :image

	has_attached_file :image, styles: { 
		large: "700x700>",
		small: "225x225#",
		thumb: "50x50#"
	}

  validate :file_dimensions, :if => :match, :unless => "errors.any?", on: :create

	belongs_to :user

	has_many :type_photos

  def file_dimensions
    dimensions = Paperclip::Geometry.from_file(self.image.queued_for_write[:original].path)
    if dimensions.width < 700 || dimensions.height < 700
      errors.add(:image, 'Both width and height must be at least 700 pixels')
    end
  end

  def match
    self.is_user
  end 
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController 
	before_filter :authenticate_user!
	before_filter :update_last_seen

	def index 
		if params[:user_id]
			@viewed_user = User.find(params[:user_id])
			@photos = @viewed_user.photos.where(is_user: true)
			profile_index = @photos.find_index { |p| p.is_profile_pic == true }
			unless profile_index.nil? 
				photo_end = profile_index + 1 
				@photos = [@photos[profile_index]] + @photos[0...profile_index] + @photos[photo_end..-1]
			end
			@photos
		end
	end 


	def new
		@photo = Photo.new
	end

	def create 
		@photo = Photo.new(params[:photo])

		@photo.user_id = current_user.id 

		# take care of existing profile pics, don't forget to do this on update and delete!
		if @photo.is_profile_pic
			current_user.photos.each do |photo| 
				photo.is_profile_pic = false
				photo.save!
			end
		end

		if @photo.save
			flash[:notice] = 'Photo added!'
			redirect_to :back
		else
			flash[:notice] = 'Image did not save. Both width and height must be at least 700 pixels.'
			redirect_to :back
		end
	end

	def show 
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = Photo.find(params[:id])

		if params[:change_profile_pic]
			current_user.photos.each do |photo| 
				photo.is_profile_pic = false
				photo.save!
			end
			@photo.is_profile_pic = true 
			@photo.save!
		end

		render nothing: true
	end


	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy

		if request.xhr? 
			render nothing: true
		else
			flash[:notice] = 'Photo deleted!'
			redirect_to :back
		end
	end
end

app/views/photos/_add_type_photo.html.erb
<div class="type-photo-upload"> 
  <%= f.hidden_field :photo_age, value: 0 %> 
  <%= f.hidden_field :is_user, value: "false" %> 
  <%= f.hidden_field :approved, value: "true" %> 
  <%= f.hidden_field :single_person, value: "true" %> 
  <%= f.hidden_field :photo_type, value: "face" %> 
  <%= f.hidden_field :user_id, value: current_user.id %> 
  <%= f.hidden_field :is_profile_pic, value: "false" %> 
  <%= f.file_field :image %>
</div> 

app/views/photos/index.html.erb
<div class="homepage">
  
  <div class="home-header">
    <div class="page-title">
      <h1><%= @viewed_user.username %>'s photos</h1>
    </div> 
  </div>

  <div class="photo-list"> 
    <% @photos.each do |photo| %>
      <div class="single-photo-display" id="single-photo-<%= photo.id %>">

    	  <img src="<%= photo.image.url(:large) %>" height="700px" width="700px">
        <% if @viewed_user.id == current_user.id %>
          <div class="photo-actions">
            <% if photo.is_profile_pic %>
              <div class="btn disabled primary-selected" id="photo-primary-<%= photo.id %>">Profile Pic</div>
            <% else %>
              <div class="btn primary" id="photo-primary-<%= photo.id %>">Make Primary</div>
            <% end %>
            <div class="btn delete" id="photo-delete-<%= photo.id %>">Delete</div>
          </div> 
        <%end%>

      </div>
    <% end %> 
  </div>


</div>


<script>
  

  $(document).ready(function(){
  
    <% @photos.each do |photo| %>

      var $deleteButton = $("#photo-delete-<%= photo.id %>")

      $deleteButton.on("click", function (data) {
        var buttonId = data.toElement.id.match(/\d+$/);
        buttonId = buttonId[0].toString();

        var reallyDelete = confirm("Are you sure you want to delete this photo?")
        if (reallyDelete === true) {
          $.ajax({
            url: "<%= photo_path(photo) %>",
            type: "DELETE",
            data: {
              "photo_id": buttonId
            },
            success: function (data) {
              var photoId = "#single-photo-" + buttonId;
              $(photoId).addClass("destroyed");
            }
          })
        }

      })

      var $makePrimaryButton = $("#photo-primary-<%= photo.id %>")

      $makePrimaryButton.on("click", function (data) {
        $.ajax({
          url: "<%= photo_path(photo) %>",
          type: "PUT",
          data: {
            "photo_id": "<%= photo.id %>",
            "change_profile_pic" : true
          },
          success: function (data) {
            window.scrollTo(0,0);
            document.location.reload(true);
          }
        })
      })

    <% end %>

  });


</script

app/views/photos/new.html.erb
<div class="homepage">
	<div class="home-header group">

		<div class="page-title">
			<h1>Let's add some pics!</h1>
		</div> 
	</div>

	<div class="photo-add-form"> 
		<%= form_for(@photo, html: {multipart: true}) do |f| %>
			<%= hidden_field_tag "photo[is_user]", "true" %>
			<%= hidden_field_tag "photo[approved]", "true" %> 
			<div> 
				<%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg' %>
			</div>

			<div>
				<%= f.label :photo_age, "When was this photo taken?" %>
				<%= select_tag "photo[photo_age]", options_for_select([['This year', 0], ['Last year', 1], ['Two years ago', 2], ['Three years ago', 3], ['More than four years old', 4]])  %>
			</div>

			<div>
				<%= f.label :single_person, "Just me in this pic" %>
				<%= radio_button_tag "photo[single_person]", "true", "true" %><span class="radio-descriptor">Yes</span>
				<br>
				<%= radio_button_tag "photo[single_person]", "false" %><span class="radio-descriptor">No</span>
			</div>

			<div>
				<%= f.label :is_profile_pic, "Main profile pic?" %>
				<%= radio_button_tag "photo[is_profile_pic]", "true" %><span class="radio-descriptor">Yes</span>
				<br>
				<%= radio_button_tag "photo[is_profile_pic]", "false", "true" %><span class="radio-descriptor">No</span>
			</div>

			<div> 
				<%= f.label :photo_type, "This pic is mostly of my..." %>
				<%= radio_button_tag "photo[photo_type]", "face", "true" %><span class="radio-descriptor">Face </span><span class="radio-descriptor-subtext">(only headshots are used for face matching)</span>
				<br>
				<%= radio_button_tag "photo[photo_type]", "body" %><span class="radio-descriptor">Body</span>
				<br>
				<%= radio_button_tag "photo[photo_type]", "both" %><span class="radio-descriptor">Both</span>
				<br>
				<%= radio_button_tag "photo[photo_type]", "neither" %><span class="radio-descriptor">Neither</span>
			</div>

			<div id="submit-button">
				<%= f.submit "Add Photo", class: "btn" %>
			<div>
		<% end %> 
	</div>
</div>

app/views/photos/show.html.erb
<h1>here's a small picture</h1>
<img src="<%= @photo.image.url(:thumb) %>">
<br>
<h1>and the same one bigger</h1>
	<img src="<%= @photo.image.url(:small) %>">
<br>
<h1>and the same one bigger</h1>
	<img src="<%= @photo.image.url(:large) %>">
<br>